# Generated by Django 4.1.2 on 2022-10-26 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fleet_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bruker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="vehicle",
            name="abax_nr",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="build_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="date_km",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="last_eu_control",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="last_km",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="leasing_expiry",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="next_eu_control",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="owner",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="sted",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="tyre_hotel",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vin_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="winter_tyre",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="brand",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="reg_number",
            field=models.CharField(max_length=7, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="bruker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fleet_management.bruker",
            ),
        ),
    ]
