# Generated by Django 4.1.2 on 2022-10-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fleet_management", "0002_bruker_vehicle_abax_nr_vehicle_build_year_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="location",
            new_name="department",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="bruker",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="sted",
        ),
        migrations.DeleteModel(
            name="Bruker",
        ),
    ]
