# Generated by Django 4.1.2 on 2022-11-02 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fleet_management", "0003_rename_location_vehicle_department_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department_name",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="date_km",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="last_eu_control",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="leasing_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="next_eu_control",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="winter_tyre",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="fleet_management.department",
            ),
        ),
    ]
