# Generated by Django 4.1.2 on 2022-11-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet_management", "0004_department_alter_vehicle_date_km_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
