# Generated by Django 4.1.2 on 2022-11-15 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fleet_management", "0008_contract_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fleet_management.vehicle",
            ),
        ),
    ]
